#!/bin/sh

set -u

usage () {
    cat <<'EOF'
usage: $0 [-c config file] [-h source host] [-p source path] [-u url to last update info]
          [-d dest dir path] [-o rsync option] [-l logfile] [-L lock dir]

 -c: specify configuration file path

 -h: specify hostname serves original data

 -p: specify module and path name of source host

 -u: url that returns last update date

 -d: local directory path to store data

 -o: specify rsync option
     default is "--quiet -rlpt --hard-links --delete --delete-after --safe-links --timeout 600"

 -l: specify log file path
     default is '/var/log/rsync/mirror.`hostname`_`path`.log'

 -L: specify lock directory path
     default is '/var/lock/mirror.`hostname`_`path`.lock'

EOF
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

warn () {
    >&2 echo "$0: $@"
}

isexist () {
    [ -e "$1" ] && return 0
    warn "$1 does not exist"
    exit 1
}


# initialize
INSTANCE="$1"
CONFFILE="/etc/mirror/${INSTANCE}.conf"
if [ -f "./${INSTANCE}.conf" ]; then
    CONFFILE="./${INSTANCE}.conf"
fi
isexist "$CONFFILE"

# set default vars
LOGDIR='/var/log/rsync'
LOCKDIR='/var/lock'

# load configuration
. $CONFFILE

# check configuration
checkvar () {
    unset _checkvar
    eval "_checkvar=\$$1"
    if [ -z "$_checkvar" ]; then
        warn "$1 is need to be set in '$CONFFILE'"
        exit 1
    fi
}

checkvar MIRRORHOST
checkvar MIRRORTARGET

[ -z "$RSYNCOPT" ] && {
    RSYNCOPT="--quiet -rlpt --hard-links --delete --delete-after --safe-links --timeout 600"
}
MIRRORLOG=$LOGDIR/mirror.${INSTANCE}.log

isexist "$MIRRORTARGET"


# set lock
LOCKDIR=$LOCKDIR/mirror.${INSTANCE}.lock
cleanup () {
    rmdir $LOCKDIR
}

mkdir $LOCKDIR || exit 1
trap cleanup EXIT HUP INT TERM


# check connectivity of host
[ ! -z "$PINGHOST" ] && {
    ping -c 1 $PINGHOST > /dev/null
    if [ $? -ne 0 ]; then
        warn "$PINGHOST seems to be down (ping)"
        exit 1
    fi
}


# ready to rsync
rsync --log-file=$MIRRORLOG $RSYNCOPT \
    $MIRRORHOST $MIRRORTARGET

if [ $? -ne 0 ]; then
    warn "something wrong on rsync"
    exit 1
fi
