#!/bin/sh

if [ $# -lt 2 ]; then
    echo "usage: $0 source1 source2 ... target"
    exit 1
fi

warn () {
    [ -z "$1" ] && return 0
    echo -n "$0: "
    echo $1
}

RSYNCOPT="--quiet -a --compress --hard-links --xattrs --delete --force --super --numeric-ids --timeout 600"
RSYNCLOG=/var/log/backup/rsync.log

# set lock
LOCKDIR=/var/lock/rsync.lock
cleanup () {
    rmdir $LOCKDIR
}

mkdir $LOCKDIR || exit 1
trap cleanup EXIT HUP INT TERM


# read directory list and merge them to one line
# get rid of needless '/' from first and last of line
DIRLIST=""
while [ "$2" != "" ]
do
    line="$1"
    shift 1
    line=`echo $line | sed -e 's#/$##'`
    line=`echo $line | sed -e 's#^/##'`
    DIRLIST="$DIRLIST /$line"
done


# ready to rsync
rsync --log-file=$RSYNCLOG $RSYNCOPT \
    $DIRLIST $1

if [ $? -ne 0 ]; then
    warn "something wrong on rsync"
    exit 1
fi
