#!/bin/sh

set -u

usage () {
    cat <<'EOF'
usage: $0 [-c config file] [-h source host] [-p source path] [-u url to last update info]
          [-d dest dir path] [-o rsync option] [-l logfile] [-L lock dir]

 -c: specify configuration file path

 -h: specify hostname serves original data

 -p: specify module and path name of source host
     path should be end with trailing slach '/'

 -u: url that returns last update date

 -U: local file path to store last update date

 -d: local directory path to store data

 -o: specify rsync option
     default is "--quiet -rlpt --hard-links --delete --delete-after --safe-links --timeout 600"

 -l: specify log file path
     default is '/var/log/rsync/mirror.`hostname`_`path`.log'

 -L: specify lock directory path
     default is '/var/lock/mirror.`hostname`_`path`.lock'

EOF
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

warn () {
    >&2 echo "$0: $@"
}

isexist () {
    [ -e "$1" ] && return 0
    warn "$1 does not exist"
    exit 1
}


# parse commandline arguments
while getopts "c:h:p:u:U:d:o:l:L:" OPT; do
    case $OPT in
        c)  CONFFILE="$OPTARG"
            isexist "$CONFFILE"
            # load configuration
            . $CONFFILE
            ;;
        h)  SRCHOST="$OPTARG"
            ;;
        p)  SRCPATH="$OPTARG"
            ;;
        u)  LASTUPDATEURL="$OPTARG"
            ;;
        U)  LASTUPDATEFILE="$OPTARG"
            ;;
        d)  DSTPATH="$OPTARG"
            ;;
        o)  RSYNCOPT="$OPTARG"
            ;;
        l)  RSYNCLOG="$OPTARG"
            ;;
        L)  LOCKDIR="$OPTARG"
            ;;
    esac
done
shift $(( $OPTIND - 1 ))


# check configuration and set default
checkvar () {
    unset _checkvar
    set +u
    eval "_checkvar=\$$1"
    set -u
    if [ -z "$_checkvar" ]; then
        if [ $# -eq 2 ]; then
            eval "$1=\"$2\""
        else
            warn "$1 is need to be set"
            exit 1
        fi
    fi
}


# check configrations and set default value if not yet
checkvar LASTUPDATEURL ""
checkvar LASTUPDATEFILE ""
checkvar SRCHOST
checkvar SRCPATH
checkvar DSTPATH
checkvar RSYNCOPT "--quiet -rlpt --hard-links --delete --delete-after --safe-links --timeout 600"

__SRCPATH=$(echo $SRCPATH | tr '/' '_')

checkvar RSYNCLOG "/var/log/rsync/mirror.${SRCHOST}_${__SRCPATH}.log"
checkvar LOCKDIR "/var/lock/mirror.${SRCHOST}_${__SRCPATH}.lock"

isexist "$DSTPATH"


# check connectivity of host
for retry in 1 2 3; do
    ping -c 1 $SRCHOST > /dev/null 2>&1
    ret=$?
    if [ $ret -eq 0 ]; then
        break
    else
        sleep 1s
        continue
    fi
done
if [ $ret -ne 0 ]; then
    warn "$SRCHOST seems to be down (ping)"
    exit 1
fi


# check is there any update?
if [ -f "$LASTUPDATEFILE" -a -n "$LASTUPDATEURL" ]; then
    serversynctime=$(curl --silent -f $LASTUPDATEURL)
    localsynctime=$(cat $LASTUPDATEFILE)
    if [ -z "$serversynctime" ]; then
        warn "something wrong on retrieving server sync time"
        exit 1
    fi
    if [ -n "$localsynctime" ]; then
        if [ "$serversynctime" -le "$localsynctime" ]; then
            warn "$SRCHOST::$SRCPATH has no update"
            exit 0
        fi
    fi
fi


# set lock
cleanup () {
    rmdir $LOCKDIR
    exit
}

mkdir $LOCKDIR || exit 1
trap exit HUP INT QUIT PIPE TERM
trap cleanup EXIT


# ready to rsync
rsync --log-file=$RSYNCLOG $RSYNCOPT \
    $SRCHOST::$SRCPATH $DSTPATH

if [ $? -ne 0 ]; then
    warn "something wrong on rsync"
    exit 1
fi
